import type { TVinfoItem } from "@/components/tariff-page/TVBlock";

export const TVinfoItems: TVinfoItem[] = [
    { id: 0, name: '?', channels: '0', movies: '0', show: false, button: 'Promo 14 днів', string1: '0 каналiв для ', string2: 'любителів ТБ, а також ', string3: 'колекцiя фiльмiв, ', string4: 'мультикiв та серiалiв', from_col: 'from-[#3E3D39]', to_col: 'to-[#1B211F]', button_col: 'bg-[#303030]' },
    { id: 1, name: 'Легка', channels: '298', movies: '10000+', show: true, button: 'Promo 14 днів', string1: '298 каналiв для ', string2: 'любителів ТБ, а також ', string3: 'колекцiя фiльмiв, ', string4: 'мультикiв та серiалiв', from_col: 'from-[#3E3D39]', to_col: 'to-[#1B211F]', button_col: 'bg-[#303030]' },
    { id: 2, name: 'Оптимальна', channels: '389', movies: '11400+', show: true, button: 'Спробувати за 1 грн*', string1: '389 каналiв i фiльми, ', string2: 'серiали, мультики топових ', string3: 'кiностудiй для поцiновувачiв ', string4: 'кiно', from_col: 'from-[#333A4C]', to_col: 'to-[#25283B]', button_col: 'bg-[#323A4B]' },
    { id: 3, name: 'Максимальна', channels: '421', movies: '14700+', show: true, button: 'Promo 14 днів', string1: '421 канал i максимум ', string2: 'фiльмiв та мультикiв, ', string3: 'серiали вiд НВО, весь ', string4: 'спорт', from_col: 'from-[#523F94]', to_col: 'to-[#1D3032]', button_col: 'bg-[#33365A]' },
    { id: 4, name: 'Спорт', channels: '36', movies: '3537+', show: true, button: 'Promo 14 днів', string1: '36 каналiв для ', string2: 'любителiв спорту. Лiга ', string3: 'чемпiонiв, АПЛ, бокс, ', string4: 'Формула-1 та iн', from_col: 'from-[#1E3230]', to_col: 'to-[#203D39]', button_col: 'bg-[#1E3331]' },
    { id: 5, name: 'Кіно+', channels: '35', movies: '12000+', show: true, button: 'Promo 14 днів', string1: '35 інтерактивних ', string2: 'фільмових каналів, ', string3: 'колекція фільмів, ', string4: 'серіалів та мультиків', from_col: 'from-[#1E2632]', to_col: 'to-[#202C3D]', button_col: 'bg-[#1E2734]' },
];