image: alpine:latest
before_script:
  - apk add --no-cache openssh-client # Install SSH client in the Docker image
  - eval $(ssh-agent -s) # Start the SSH agent
  - chmod 400 "$SSH_PRIVATE_KEY"
  - chmod 400 "$SSH_PRIVATE_KEY_PROD"
  - ssh-add "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY_PROD"
  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan server2.icstudio.online >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  only:
    - testing
  script: 
    - ssh batyevka@server2.icstudio.online "bash bb.sh" -vvv
    - echo "Deployed on DevServer. Bracnh testing."

deploy-dev:
  stage: deploy
  only:
    - master
  script: 
    - ssh batyevka@server2.icstudio.online "bash bb-test.sh" -vvv
    - echo "Deployed on DevServer. Brach master"
deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - ssh ssh www-root@srv.batyevka.net "bash bb-prod.sh" -vvv
    - echo "Deployed on Production"